%isg_manual
( Program to run manual mode with possibility to 
( switch kinematic transformation ON/OFF

N0001 #VAR
N0002   V.L.FLAG_TRAFO
N0003   V.L.V_TIP_CART_MM
N0004   V.L.V_TIP_CART_DEG
N0005   V.L.V_TIP_AXIS_DEG

N0006   V.L.V_JOG_CART_MM
N0007   V.L.V_JOG_CART_DEG
N0008   V.L.V_JOG_AXIS_DEG

N0010   V.L.JOG_WIDTH_1
N0011   V.L.JOG_WIDTH_2
N0012   V.L.JOG_WIDTH_3
N0013   V.L.JOG_WIDTH_4
N0020 #ENDVAR

(Settings for continuous jog)
N0110 V.L.V_TIP_CART_MM =6000.0 (cartesian velocity for X,Y,Z in mm/min, EN775: <250mm/s in T1 mode)
N0120 V.L.V_TIP_CART_DEG=360.0  (cartesian velocity for A,B,C in °/min)
N0130 V.L.V_TIP_AXIS_DEG=360.0  (axes velocity in °/min)

(Settings for incremental jog)
N0110 V.L.V_JOG_CART_MM =6000.0 (cartesian velocity for X,Y,Z in mm/min, EN775: <250mm/s in T1 mode)
N0120 V.L.V_JOG_CART_DEG=360.0  (cartesian velocity for A,B,C in °/min)
N0240 V.L.V_JOG_AXIS_DEG=360.0  (axes velocity in °/min)
N0210 V.L.JOG_WIDTH_1=0.5       (jog width in mm or °)
N0210 V.L.JOG_WIDTH_2=1.0
N0210 V.L.JOG_WIDTH_3=3.0
N0210 V.L.JOG_WIDTH_4=10.0


( Inverse Initialisation at first call
N1010 $IF V.E.SYS_HMI_BOOL[0] == TRUE
N1011   V.L.FLAG_TRAFO = FALSE
N1012 $ELSE
N1013   V.L.FLAG_TRAFO = TRUE
N1014 $ENDIF

N1020 $WHILE 1

N1030   $IF V.E.SYS_HMI_BOOL[0] != V.L.FLAG_TRAFO

N1040     G202
N1050     #SET DEC LR SOLL
N1060     V.L.FLAG_TRAFO = V.E.SYS_HMI_BOOL[0]  

N1100     $IF V.E.SYS_HMI_BOOL[0] == TRUE

N1110       ( #MSG SYN ["TRAFO ON"] )
N1120       #TRAFO ON

N1131       #SET TIP[V.L.V_TIP_CART_MM]  X
N1132       #SET TIP[V.L.V_TIP_CART_MM]  Y
N1133       #SET TIP[V.L.V_TIP_CART_MM]  Z
N1135       #SET TIP[V.L.V_TIP_CART_DEG] A
N1136       #SET TIP[V.L.V_TIP_CART_DEG] B
N1137       #SET TIP[V.L.V_TIP_CART_DEG] C

N1141       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_2,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_3,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_4,V.L.V_JOG_CART_MM]  ] X
N1142       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_2,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_3,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_4,V.L.V_JOG_CART_MM]  ] Y
N1143       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_2,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_3,V.L.V_JOG_CART_MM]  [V.L.JOG_WIDTH_4,V.L.V_JOG_CART_MM]  ] Z
N1145       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_CART_DEG] ] A
N1146       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_CART_DEG] ] B
N1147       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_CART_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_CART_DEG] ] C

N1150       G201  #ACHSE[X, Y, Z, A, B, C]

N1200     $ELSE

N1210       ( #MSG SYN ["TRAFO OFF"] )
N1220       #TRAFO OFF

N1231       #SET TIP[V.L.V_TIP_AXIS_DEG] X
N1232       #SET TIP[V.L.V_TIP_AXIS_DEG] Y
N1233       #SET TIP[V.L.V_TIP_AXIS_DEG] Z
N1234       #SET TIP[V.L.V_TIP_AXIS_DEG] A
N1235       #SET TIP[V.L.V_TIP_AXIS_DEG] B
N1236       #SET TIP[V.L.V_TIP_AXIS_DEG] C

N1241       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_AXIS_DEG] ] X
N1242       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_AXIS_DEG] ] Y
N1243       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_AXIS_DEG] ] Z
N1245       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_AXIS_DEG] ] A
N1246       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_AXIS_DEG] ] B
N1247       #SET JOG[ [V.L.JOG_WIDTH_1,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_2,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_3,V.L.V_JOG_AXIS_DEG] [V.L.JOG_WIDTH_4,V.L.V_JOG_AXIS_DEG] ] C

N1250       G201  #ACHSE[X, Y, Z, A, B, C]

N1300     $ENDIF

N1400   $ENDIF
 
N1500 $ENDWHILE
N1600 M29
